on:
  push:
    branches:
      - master

jobs:
  build_release:
    name: Build Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        use-cross: true
      - run: cargo build --release --all-features
